name: English-Reading

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: kiendtph12640@gmail.com
          password: Matkhau123@
      - name: Build
        run: docker build -t reactjs-basic .
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: kiendt12640/reactjs-basic:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Verify SSH Connection
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no root@172.208.9.27 "echo 'SSH Connection Successful'"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no root@172.208.9.27 << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-basic:${{ github.sha }}
            docker stop reactjs-container || true
            docker rm reactjs-container || true
            docker run -d -p 3010:3000 --name reactjs-container ${{ secrets.DOCKER_USERNAME }}/reactjs-basic:${{ github.sha }}
          EOF
